1. Numpy exercises

a. Create a null vector of size 10 but the fifth value which is 1

In [2]:
import numpy as np
x = np.zeros(10)
x[5] = 1
print(x)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


b. Create a vector with values ranging from 10 to 49

In [5]:
y = np.arange(10,50)
print(y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


c. Reverse a vector (first element becomes last)

In [32]:
c = np.flip(y)
print(c)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


d. Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
m = np.arange(0,9).reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


e. Find indices of non-zero elements from [1,2,0,0,4,0]

In [34]:
e = np.array([1,2,0,0,4,0])
np.nonzero(e)

(array([0, 1, 4], dtype=int64),)

f. Create a random vector of size 30 and find the mean value

In [12]:
f = np.random.random(30)
print(f)
np.mean(f)

[0.21384439 0.81635798 0.66791054 0.67379362 0.88322695 0.20196431
 0.72548952 0.68539325 0.47536509 0.32507692 0.80457791 0.32110471
 0.58888707 0.49079035 0.41805361 0.14580538 0.77416229 0.41771734
 0.47383498 0.73756249 0.22244057 0.54222449 0.04829678 0.62056736
 0.31838932 0.51628659 0.28496254 0.10859763 0.14137387 0.21649588]


0.46201845744249337

g. Create a 2d array with 1 on the border and 0 inside

In [15]:
g = np.ones((6,6))
print(g)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [16]:
g[1:-1,1:-1] = 0
print(g)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


h. Create a 8x8 matrix and fill it with a checkerboard pattern

In [19]:
h = np.zeros((8,8))
h[1::2,::2] = 1 #Columns: take index 1 included to 2 non included, step of 2, = 1
print(h)
h[::2,1::2] = 1 #Rows
print(h)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


i. Create a checkerboard 8x8 matrix using the tile function

In [24]:
i = np.array([0,1])
np.tile(i,(8,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

j. Given a 1D array, negate all elements which are between 3 and 8, in place

In [27]:
Z = np.arange(11)
i = np.logical_and((Z>2),(Z<8))
Z[i] *= -1
print(Z)

[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]


In [28]:
Z = np.arange(11)
Z[3:9] = np.multiply(Z[3:9],-1)

print(Z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


k. Create a random vector of size 10 and sort it

In [35]:
Z = np.random.random(10)
Z = np.sort(k)
print(Z)

[0.09423393 0.23874853 0.36951827 0.40800651 0.49767754 0.56251656
 0.65869865 0.83447629 0.90369683 0.95770442]


l. Consider two random array A anb B, check if they are equal

In [38]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
comparison = A==B
equal = comparison.all()
print(equal)

False


m. How to convert an integer (32 bits) array into a float (32 bits) in place?

In [40]:
Z = np.arange(10, dtype=np.int32)
print(Z.dtype)
Z = Z.astype(np.float32)
print(Z.dtype)

int32
float32


n. How to get the diagonal of a dot product?

In [43]:
A = np.arange(9).reshape(3,3)
print(A)
B = A + 1
print(B)
C = np.dot(A,B)
print(C)
D = np.diag(C)
print(D)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]
[ 18  66 132]
